# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a24be7c423611d229da1e39dce1f4e10087f2ef0e769c3298201aafc4847532163d7424b95f777d21dc6d57dd5ac2a97948910e42148012b5ad45a430bad6278

test:
  secret_key_base: 9a7f4061f4e653a588123e4208d1cc6100b52f6cc20c8b898bf0f8c083a77b7e8aca51855394da0e671fb16efd43a2073dac5759558fefb5e515969be298dce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
